RideScheduler.TDS.Validator.Web/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using System.Diagnostics;

namespace RideScheduler.TDS.Validator.Web.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RideScheduler.TDS.Validator.Web/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

using Newtonsoft.Json.Linq;
using Newtonsoft.Json.Schema;

using System.Net;
using System.Text;

namespace RideScheduler.TDS.Validator.Web.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            ViewData["Code"] = @"{
    ""tripStatusChange"": {
        ""tripTicketId"": ""3fa85f64-5717-4562-b3fc-2c963f66afa6"",
        ""status"": ""Cancel"",
        ""reasonDescription"": ""string"",
        ""canceledBy"": ""OrderingClient""
    }
}";
        }

        public void OnPost([FromForm] string code)
        {
            ViewData["Validation"] = JsonValidate(code);
            ViewData["Code"] = code;
        }

        public static (bool?, List<ValidationError>) JsonValidate(string message)
        {
            try
            {
                var schemaJson = JSON.GetSchema();

                // load schema
                JSchema schema = JSchema.Parse(schemaJson);
                JToken json = JToken.Parse(message);

                // validate json
                bool valid = json.IsValid(schema, out IList<ValidationError> errors);

                // return error messages and line info to the browser
                return (valid, errors.ToList());

            }
            catch (Exception e)
            {
                return (false, new List<ValidationError>() { new ValidationError() { } });
            }
        }

        public ActionResult OnPostDownload()
        {
            var schemaJson = Encoding.Unicode.GetBytes(JSON.GetSchema());
            return File(schemaJson, "application/octet-stream", "schema.json");
        }
    }
}

RideScheduler.TDS.Validator.Web/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RideScheduler.TDS.Validator.Web.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RideScheduler.TDS.Validator.Web/Pages/Index.cshtml
@page
@using Newtonsoft.Json.Schema
@using Newtonsoft.Json
@using Newtonsoft.Json.Linq
@model IndexModel
@{
    ViewData["Title"] = "TDS Validator : By RideScheduler";
    (bool?, List<ValidationError>) validation = ((bool?, List<ValidationError>))(ViewData["Validation"] ?? ((bool?)null, new List<ValidationError>()));
    string schemaJson = JSON.GetSchema();
    JToken json = JToken.Parse(schemaJson);
    var title = json["title"].Value<string>();
    var description = json["description"].Value<string>();
}
<style>
    .CodeMirror {
        border: 1px solid #cccccc;
        border-radius: 5px;
        min-height: 500px;
    }
</style>
<form method="post" asp-page-handler="Download">
    <div style="text-align: right"><button class="btn btn-link" type="submit">Download</button></div>
</form>
<form method="post">
    <div class="text-center">
        <table style="width: 100%;">
            <tr >
                <td rowspan="2" >
                    <h1 class="display-4" style="white-space: nowrap;">TDS Validator</h1>
                </td>
                <td><h5 title="@description">@title</h5></td>
            </tr>
            <tr >
                <td >
                    <p style="text-align: justify; margin-left: 20px; line-height: normal;">
                        The TDS validator was developed by RideScheduler for the RideNoCo coordination project. That coordination project was a collaborative effort between the North Front Range Metropolitan Planning Organization (NFRMPO), RideScheduler, RideSheet, Spedsta and TransitPlus. The validator tool utilizes the <a href="https://github.com/RideNoCo/drt-tds/blob/main/spec/schema.json" target="_blank" title="View schema.json">RideNoCo TDS schema</a> which is based on the XML Schema from tcrp.demandtrans.com_TCRPSchema.
                    </p>
                </td>
            </tr>
        </table>
    </div>
    <textarea id="code" name="code" class="border-dark">@ViewData["Code"]</textarea>
    <div style="text-align: right; margin: 10px 0;">
        <button type="submit" class="btn btn-lg btn-primary ">Validate</button>
        <a class="btn btn-lg btn-outline-danger" href="~/">Reset</a>
    </div>
</form>

@functions
{
    string GetValidateWrapperClass(bool? valid)
    {
        return valid switch
        {
            true => "alert-success",
            false => "alert-danger",
            _ => ""
        };
    }

    string GetValidateTitle(bool? valid)
    {
        return valid switch
        {
            true => "<h4>Valid JSON</h4>",
            false => "<h4>Validation Failed</h4>",
            _ => ""
        };
    }


    void BuildMessage(ValidationError i)
    {
        Type? valTtype = i?.Value?.GetType();
        <li>
            <div>@i.SchemaId @i.ErrorType (Line @i.LineNumber, Pos @i.LinePosition)</div>
            <div style="margin-left: 20px"><b>@i.Message</b></div>
            <div style="margin-left: 40px">
                @i.Path:
                @switch (true)
                {
                    case true when valTtype == typeof(List<string>):
                        <span>@JsonConvert.SerializeObject(i.Value)</span>
                        break;
                    default:
                        <span>@i.Value?.ToString()</span>
                        break;
                }
            </div>
        </li>
    }
}

<div class="alert @GetValidateWrapperClass(validation.Item1)">
    @Html.Raw(GetValidateTitle(validation.Item1))
    <ul>
        @foreach (var i in validation.Item2)
        {
            BuildMessage(i);
        }
    </ul>
</div>

<script>
    var editor = CodeMirror.fromTextArea(document.getElementById("code"), {
        lineNumbers: true,
        matchBrackets: true,
        continueComments: "Enter",
        mode: "JSON",
        extraKeys: { "Ctrl-Q": "toggleComment" }
    });
</script>

RideScheduler.TDS.Validator.Web/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RideScheduler.TDS.Validator.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <script src="~/lib/codemirror/javascript.js"></script>
    <script src="~/lib/codemirror/codemirror.js"></script>
    <link href="~/lib/codemirror/codemirror.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RideScheduler.TDS.Validator.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RideScheduler.TDS.Validator.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav> *@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <div style="text-align: center; margin: 10px 0;">
                <img src="~/img/poweredby.png" /> <br/>
            </div>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container" style="text-align: center">
            &copy; @DateTime.Today.Year - RideScheduler&nbsp;&nbsp;&nbsp;&nbsp;<img src="https://vsrm.dev.azure.com/EdgeFish/_apis/public/Release/badge/79f3e50b-abcf-4ee3-a4de-7ae05d447156/18/41" alt="buld status" />
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>